export interface CountryCode {
  code: string;
  country: string;
  flag: string;
  name: string;
  format: string;
}

const COUNTRY_CODES: CountryCode[] = [
  // Europe
  { code: "+34", country: "ES", flag: "\u{1F1EA}\u{1F1F8}", name: "España", format: "XXX XX XX XX" },
  { code: "+44", country: "GB", flag: "\u{1F1EC}\u{1F1E7}", name: "Reino Unido", format: "XXXX XXXXXX" },
  { code: "+33", country: "FR", flag: "\u{1F1EB}\u{1F1F7}", name: "Francia", format: "X XX XX XX XX" },
  { code: "+49", country: "DE", flag: "\u{1F1E9}\u{1F1EA}", name: "Alemania", format: "XXX XXXXXXXX" },
  { code: "+39", country: "IT", flag: "\u{1F1EE}\u{1F1F9}", name: "Italia", format: "XXX XXX XXXX" },
  { code: "+351", country: "PT", flag: "\u{1F1F5}\u{1F1F9}", name: "Portugal", format: "XXX XXX XXX" },
  { code: "+31", country: "NL", flag: "\u{1F1F3}\u{1F1F1}", name: "Países Bajos", format: "X XXXXXXXX" },
  { code: "+32", country: "BE", flag: "\u{1F1E7}\u{1F1EA}", name: "Bélgica", format: "XXX XX XX XX" },
  { code: "+41", country: "CH", flag: "\u{1F1E8}\u{1F1ED}", name: "Suiza", format: "XX XXX XX XX" },
  { code: "+43", country: "AT", flag: "\u{1F1E6}\u{1F1F9}", name: "Austria", format: "XXX XXXXXXX" },
  { code: "+46", country: "SE", flag: "\u{1F1F8}\u{1F1EA}", name: "Suecia", format: "XX XXX XX XX" },
  { code: "+47", country: "NO", flag: "\u{1F1F3}\u{1F1F4}", name: "Noruega", format: "XXX XX XXX" },
  { code: "+45", country: "DK", flag: "\u{1F1E9}\u{1F1F0}", name: "Dinamarca", format: "XX XX XX XX" },
  { code: "+358", country: "FI", flag: "\u{1F1EB}\u{1F1EE}", name: "Finlandia", format: "XX XXX XXXX" },
  { code: "+48", country: "PL", flag: "\u{1F1F5}\u{1F1F1}", name: "Polonia", format: "XXX XXX XXX" },
  { code: "+420", country: "CZ", flag: "\u{1F1E8}\u{1F1FF}", name: "Chequia", format: "XXX XXX XXX" },
  { code: "+421", country: "SK", flag: "\u{1F1F8}\u{1F1F0}", name: "Eslovaquia", format: "XXX XXX XXX" },
  { code: "+36", country: "HU", flag: "\u{1F1ED}\u{1F1FA}", name: "Hungría", format: "XX XXX XXXX" },
  { code: "+40", country: "RO", flag: "\u{1F1F7}\u{1F1F4}", name: "Rumania", format: "XXX XXX XXX" },
  { code: "+359", country: "BG", flag: "\u{1F1E7}\u{1F1EC}", name: "Bulgaria", format: "XX XXX XXXX" },
  { code: "+385", country: "HR", flag: "\u{1F1ED}\u{1F1F7}", name: "Croacia", format: "XX XXX XXXX" },
  { code: "+386", country: "SI", flag: "\u{1F1F8}\u{1F1EE}", name: "Eslovenia", format: "XX XXX XXX" },
  { code: "+381", country: "RS", flag: "\u{1F1F7}\u{1F1F8}", name: "Serbia", format: "XX XXX XXXX" },
  { code: "+387", country: "BA", flag: "\u{1F1E7}\u{1F1E6}", name: "Bosnia y Herzegovina", format: "XX XXX XXX" },
  { code: "+382", country: "ME", flag: "\u{1F1F2}\u{1F1EA}", name: "Montenegro", format: "XX XXX XXX" },
  { code: "+389", country: "MK", flag: "\u{1F1F2}\u{1F1F0}", name: "Macedonia del Norte", format: "XX XXX XXX" },
  { code: "+355", country: "AL", flag: "\u{1F1E6}\u{1F1F1}", name: "Albania", format: "XX XXX XXXX" },
  { code: "+383", country: "XK", flag: "\u{1F1FD}\u{1F1F0}", name: "Kosovo", format: "XX XXX XXX" },
  { code: "+30", country: "GR", flag: "\u{1F1EC}\u{1F1F7}", name: "Grecia", format: "XXX XXX XXXX" },
  { code: "+90", country: "TR", flag: "\u{1F1F9}\u{1F1F7}", name: "Turquía", format: "XXX XXX XXXX" },
  { code: "+357", country: "CY", flag: "\u{1F1E8}\u{1F1FE}", name: "Chipre", format: "XX XXXXXX" },
  { code: "+356", country: "MT", flag: "\u{1F1F2}\u{1F1F9}", name: "Malta", format: "XXXX XXXX" },
  { code: "+354", country: "IS", flag: "\u{1F1EE}\u{1F1F8}", name: "Islandia", format: "XXX XXXX" },
  { code: "+353", country: "IE", flag: "\u{1F1EE}\u{1F1EA}", name: "Irlanda", format: "XX XXX XXXX" },
  { code: "+352", country: "LU", flag: "\u{1F1F1}\u{1F1FA}", name: "Luxemburgo", format: "XXX XXX XXX" },
  { code: "+377", country: "MC", flag: "\u{1F1F2}\u{1F1E8}", name: "Mónaco", format: "XXXX XXXX" },
  { code: "+376", country: "AD", flag: "\u{1F1E6}\u{1F1E9}", name: "Andorra", format: "XXX XXX" },
  { code: "+378", country: "SM", flag: "\u{1F1F8}\u{1F1F2}", name: "San Marino", format: "XXX XXXXXXX" },
  { code: "+423", country: "LI", flag: "\u{1F1F1}\u{1F1EE}", name: "Liechtenstein", format: "XXX XXX XXXX" },
  { code: "+370", country: "LT", flag: "\u{1F1F1}\u{1F1F9}", name: "Lituania", format: "XXX XXXXX" },
  { code: "+371", country: "LV", flag: "\u{1F1F1}\u{1F1FB}", name: "Letonia", format: "XX XXX XXX" },
  { code: "+372", country: "EE", flag: "\u{1F1EA}\u{1F1EA}", name: "Estonia", format: "XXXX XXXX" },
  { code: "+375", country: "BY", flag: "\u{1F1E7}\u{1F1FE}", name: "Bielorrusia", format: "XX XXX XX XX" },
  { code: "+380", country: "UA", flag: "\u{1F1FA}\u{1F1E6}", name: "Ucrania", format: "XX XXX XX XX" },
  { code: "+373", country: "MD", flag: "\u{1F1F2}\u{1F1E9}", name: "Moldavia", format: "XXXX XXXX" },
  { code: "+7", country: "RU", flag: "\u{1F1F7}\u{1F1FA}", name: "Rusia", format: "XXX XXX XX XX" },
  // Americas
  { code: "+1", country: "US", flag: "\u{1F1FA}\u{1F1F8}", name: "Estados Unidos", format: "XXX XXX XXXX" },
  { code: "+1", country: "CA", flag: "\u{1F1E8}\u{1F1E6}", name: "Canadá", format: "XXX XXX XXXX" },
  { code: "+52", country: "MX", flag: "\u{1F1F2}\u{1F1FD}", name: "México", format: "XX XXXX XXXX" },
  { code: "+502", country: "GT", flag: "\u{1F1EC}\u{1F1F9}", name: "Guatemala", format: "XXXX XXXX" },
  { code: "+503", country: "SV", flag: "\u{1F1F8}\u{1F1FB}", name: "El Salvador", format: "XXXX XXXX" },
  { code: "+504", country: "HN", flag: "\u{1F1ED}\u{1F1F3}", name: "Honduras", format: "XXXX XXXX" },
  { code: "+505", country: "NI", flag: "\u{1F1F3}\u{1F1EE}", name: "Nicaragua", format: "XXXX XXXX" },
  { code: "+506", country: "CR", flag: "\u{1F1E8}\u{1F1F7}", name: "Costa Rica", format: "XXXX XXXX" },
  { code: "+507", country: "PA", flag: "\u{1F1F5}\u{1F1E6}", name: "Panamá", format: "XXXX XXXX" },
  { code: "+53", country: "CU", flag: "\u{1F1E8}\u{1F1FA}", name: "Cuba", format: "X XXX XXXX" },
  { code: "+509", country: "HT", flag: "\u{1F1ED}\u{1F1F9}", name: "Haití", format: "XXXX XXXX" },
  { code: "+1809", country: "DO", flag: "\u{1F1E9}\u{1F1F4}", name: "Rep. Dominicana", format: "XXX XXXX" },
  { code: "+1787", country: "PR", flag: "\u{1F1F5}\u{1F1F7}", name: "Puerto Rico", format: "XXX XXXX" },
  { code: "+1876", country: "JM", flag: "\u{1F1EF}\u{1F1F2}", name: "Jamaica", format: "XXX XXXX" },
  { code: "+1868", country: "TT", flag: "\u{1F1F9}\u{1F1F9}", name: "Trinidad y Tobago", format: "XXX XXXX" },
  { code: "+501", country: "BZ", flag: "\u{1F1E7}\u{1F1FF}", name: "Belice", format: "XXX XXXX" },
  { code: "+54", country: "AR", flag: "\u{1F1E6}\u{1F1F7}", name: "Argentina", format: "XX XXXX XXXX" },
  { code: "+55", country: "BR", flag: "\u{1F1E7}\u{1F1F7}", name: "Brasil", format: "XX XXXXX XXXX" },
  { code: "+56", country: "CL", flag: "\u{1F1E8}\u{1F1F1}", name: "Chile", format: "X XXXX XXXX" },
  { code: "+57", country: "CO", flag: "\u{1F1E8}\u{1F1F4}", name: "Colombia", format: "XXX XXX XXXX" },
  { code: "+58", country: "VE", flag: "\u{1F1FB}\u{1F1EA}", name: "Venezuela", format: "XXX XXX XXXX" },
  { code: "+51", country: "PE", flag: "\u{1F1F5}\u{1F1EA}", name: "Perú", format: "XXX XXX XXX" },
  { code: "+593", country: "EC", flag: "\u{1F1EA}\u{1F1E8}", name: "Ecuador", format: "XX XXX XXXX" },
  { code: "+591", country: "BO", flag: "\u{1F1E7}\u{1F1F4}", name: "Bolivia", format: "X XXX XXXX" },
  { code: "+595", country: "PY", flag: "\u{1F1F5}\u{1F1FE}", name: "Paraguay", format: "XXX XXX XXX" },
  { code: "+598", country: "UY", flag: "\u{1F1FA}\u{1F1FE}", name: "Uruguay", format: "X XXX XXXX" },
  { code: "+592", country: "GY", flag: "\u{1F1EC}\u{1F1FE}", name: "Guyana", format: "XXX XXXX" },
  { code: "+597", country: "SR", flag: "\u{1F1F8}\u{1F1F7}", name: "Surinam", format: "XXX XXXX" },
  // Asia
  { code: "+86", country: "CN", flag: "\u{1F1E8}\u{1F1F3}", name: "China", format: "XXX XXXX XXXX" },
  { code: "+81", country: "JP", flag: "\u{1F1EF}\u{1F1F5}", name: "Japón", format: "XX XXXX XXXX" },
  { code: "+82", country: "KR", flag: "\u{1F1F0}\u{1F1F7}", name: "Corea del Sur", format: "XX XXXX XXXX" },
  { code: "+91", country: "IN", flag: "\u{1F1EE}\u{1F1F3}", name: "India", format: "XXXXX XXXXX" },
  { code: "+92", country: "PK", flag: "\u{1F1F5}\u{1F1F0}", name: "Pakistán", format: "XXX XXXXXXX" },
  { code: "+880", country: "BD", flag: "\u{1F1E7}\u{1F1E9}", name: "Bangladés", format: "XXXX XXXXXX" },
  { code: "+94", country: "LK", flag: "\u{1F1F1}\u{1F1F0}", name: "Sri Lanka", format: "XX XXX XXXX" },
  { code: "+977", country: "NP", flag: "\u{1F1F3}\u{1F1F5}", name: "Nepal", format: "XX XXXX XXXX" },
  { code: "+93", country: "AF", flag: "\u{1F1E6}\u{1F1EB}", name: "Afganistán", format: "XX XXX XXXX" },
  { code: "+62", country: "ID", flag: "\u{1F1EE}\u{1F1E9}", name: "Indonesia", format: "XXX XXXX XXXX" },
  { code: "+60", country: "MY", flag: "\u{1F1F2}\u{1F1FE}", name: "Malasia", format: "XX XXXX XXXX" },
  { code: "+63", country: "PH", flag: "\u{1F1F5}\u{1F1ED}", name: "Filipinas", format: "XXX XXX XXXX" },
  { code: "+65", country: "SG", flag: "\u{1F1F8}\u{1F1EC}", name: "Singapur", format: "XXXX XXXX" },
  { code: "+66", country: "TH", flag: "\u{1F1F9}\u{1F1ED}", name: "Tailandia", format: "XX XXX XXXX" },
  { code: "+84", country: "VN", flag: "\u{1F1FB}\u{1F1F3}", name: "Vietnam", format: "XX XXX XX XX" },
  { code: "+95", country: "MM", flag: "\u{1F1F2}\u{1F1F2}", name: "Myanmar", format: "XX XXX XXXX" },
  { code: "+855", country: "KH", flag: "\u{1F1F0}\u{1F1ED}", name: "Camboya", format: "XX XXX XXXX" },
  { code: "+856", country: "LA", flag: "\u{1F1F1}\u{1F1E6}", name: "Laos", format: "XX XX XXX XXX" },
  { code: "+852", country: "HK", flag: "\u{1F1ED}\u{1F1F0}", name: "Hong Kong", format: "XXXX XXXX" },
  { code: "+853", country: "MO", flag: "\u{1F1F2}\u{1F1F4}", name: "Macao", format: "XXXX XXXX" },
  { code: "+886", country: "TW", flag: "\u{1F1F9}\u{1F1FC}", name: "Taiwán", format: "XXX XXX XXX" },
  { code: "+976", country: "MN", flag: "\u{1F1F2}\u{1F1F3}", name: "Mongolia", format: "XX XX XXXX" },
  { code: "+850", country: "KP", flag: "\u{1F1F0}\u{1F1F5}", name: "Corea del Norte", format: "XXX XXX XXXX" },
  // Middle East
  { code: "+971", country: "AE", flag: "\u{1F1E6}\u{1F1EA}", name: "Emiratos Árabes", format: "XX XXX XXXX" },
  { code: "+966", country: "SA", flag: "\u{1F1F8}\u{1F1E6}", name: "Arabia Saudí", format: "XX XXX XXXX" },
  { code: "+972", country: "IL", flag: "\u{1F1EE}\u{1F1F1}", name: "Israel", format: "XX XXX XXXX" },
  { code: "+962", country: "JO", flag: "\u{1F1EF}\u{1F1F4}", name: "Jordania", format: "X XXXX XXXX" },
  { code: "+961", country: "LB", flag: "\u{1F1F1}\u{1F1E7}", name: "Líbano", format: "XX XXX XXX" },
  { code: "+964", country: "IQ", flag: "\u{1F1EE}\u{1F1F6}", name: "Irak", format: "XXX XXX XXXX" },
  { code: "+98", country: "IR", flag: "\u{1F1EE}\u{1F1F7}", name: "Irán", format: "XXX XXX XXXX" },
  { code: "+963", country: "SY", flag: "\u{1F1F8}\u{1F1FE}", name: "Siria", format: "XXX XXX XXX" },
  { code: "+965", country: "KW", flag: "\u{1F1F0}\u{1F1FC}", name: "Kuwait", format: "XXXX XXXX" },
  { code: "+968", country: "OM", flag: "\u{1F1F4}\u{1F1F2}", name: "Omán", format: "XXXX XXXX" },
  { code: "+974", country: "QA", flag: "\u{1F1F6}\u{1F1E6}", name: "Catar", format: "XXXX XXXX" },
  { code: "+973", country: "BH", flag: "\u{1F1E7}\u{1F1ED}", name: "Baréin", format: "XXXX XXXX" },
  { code: "+967", country: "YE", flag: "\u{1F1FE}\u{1F1EA}", name: "Yemen", format: "XXX XXX XXX" },
  // Central Asia
  { code: "+7", country: "KZ", flag: "\u{1F1F0}\u{1F1FF}", name: "Kazajistán", format: "XXX XXX XX XX" },
  { code: "+998", country: "UZ", flag: "\u{1F1FA}\u{1F1FF}", name: "Uzbekistán", format: "XX XXX XX XX" },
  { code: "+993", country: "TM", flag: "\u{1F1F9}\u{1F1F2}", name: "Turkmenistán", format: "XX XXXXXX" },
  { code: "+996", country: "KG", flag: "\u{1F1F0}\u{1F1EC}", name: "Kirguistán", format: "XXX XXX XXX" },
  { code: "+992", country: "TJ", flag: "\u{1F1F9}\u{1F1EF}", name: "Tayikistán", format: "XX XXX XXXX" },
  { code: "+994", country: "AZ", flag: "\u{1F1E6}\u{1F1FF}", name: "Azerbaiyán", format: "XX XXX XX XX" },
  { code: "+995", country: "GE", flag: "\u{1F1EC}\u{1F1EA}", name: "Georgia", format: "XXX XX XX XX" },
  { code: "+374", country: "AM", flag: "\u{1F1E6}\u{1F1F2}", name: "Armenia", format: "XX XXX XXX" },
  // Africa
  { code: "+212", country: "MA", flag: "\u{1F1F2}\u{1F1E6}", name: "Marruecos", format: "XXXX XXXXXX" },
  { code: "+213", country: "DZ", flag: "\u{1F1E9}\u{1F1FF}", name: "Argelia", format: "XXX XX XX XX" },
  { code: "+216", country: "TN", flag: "\u{1F1F9}\u{1F1F3}", name: "Túnez", format: "XX XXX XXX" },
  { code: "+218", country: "LY", flag: "\u{1F1F1}\u{1F1FE}", name: "Libia", format: "XX XXX XXXX" },
  { code: "+20", country: "EG", flag: "\u{1F1EA}\u{1F1EC}", name: "Egipto", format: "XX XXXX XXXX" },
  { code: "+249", country: "SD", flag: "\u{1F1F8}\u{1F1E9}", name: "Sudán", format: "XX XXX XXXX" },
  { code: "+234", country: "NG", flag: "\u{1F1F3}\u{1F1EC}", name: "Nigeria", format: "XXX XXX XXXX" },
  { code: "+233", country: "GH", flag: "\u{1F1EC}\u{1F1ED}", name: "Ghana", format: "XX XXX XXXX" },
  { code: "+254", country: "KE", flag: "\u{1F1F0}\u{1F1EA}", name: "Kenia", format: "XXX XXXXXX" },
  { code: "+255", country: "TZ", flag: "\u{1F1F9}\u{1F1FF}", name: "Tanzania", format: "XXX XXX XXX" },
  { code: "+256", country: "UG", flag: "\u{1F1FA}\u{1F1EC}", name: "Uganda", format: "XXX XXX XXX" },
  { code: "+251", country: "ET", flag: "\u{1F1EA}\u{1F1F9}", name: "Etiopía", format: "XX XXX XXXX" },
  { code: "+27", country: "ZA", flag: "\u{1F1FF}\u{1F1E6}", name: "Sudáfrica", format: "XX XXX XXXX" },
  { code: "+237", country: "CM", flag: "\u{1F1E8}\u{1F1F2}", name: "Camerún", format: "XXXX XXXX" },
  { code: "+225", country: "CI", flag: "\u{1F1E8}\u{1F1EE}", name: "Costa de Marfil", format: "XX XX XXX XXX" },
  { code: "+221", country: "SN", flag: "\u{1F1F8}\u{1F1F3}", name: "Senegal", format: "XX XXX XX XX" },
  { code: "+223", country: "ML", flag: "\u{1F1F2}\u{1F1F1}", name: "Malí", format: "XX XX XX XX" },
  { code: "+226", country: "BF", flag: "\u{1F1E7}\u{1F1EB}", name: "Burkina Faso", format: "XX XX XX XX" },
  { code: "+227", country: "NE", flag: "\u{1F1F3}\u{1F1EA}", name: "Níger", format: "XX XX XX XX" },
  { code: "+228", country: "TG", flag: "\u{1F1F9}\u{1F1EC}", name: "Togo", format: "XX XX XX XX" },
  { code: "+229", country: "BJ", flag: "\u{1F1E7}\u{1F1EF}", name: "Benín", format: "XX XX XX XX" },
  { code: "+224", country: "GN", flag: "\u{1F1EC}\u{1F1F3}", name: "Guinea", format: "XXX XX XX XX" },
  { code: "+220", country: "GM", flag: "\u{1F1EC}\u{1F1F2}", name: "Gambia", format: "XXX XXXX" },
  { code: "+222", country: "MR", flag: "\u{1F1F2}\u{1F1F7}", name: "Mauritania", format: "XXXX XXXX" },
  { code: "+235", country: "TD", flag: "\u{1F1F9}\u{1F1E9}", name: "Chad", format: "XX XX XX XX" },
  { code: "+236", country: "CF", flag: "\u{1F1E8}\u{1F1EB}", name: "Rep. Centroafricana", format: "XX XX XX XX" },
  { code: "+241", country: "GA", flag: "\u{1F1EC}\u{1F1E6}", name: "Gabón", format: "X XX XX XX" },
  { code: "+242", country: "CG", flag: "\u{1F1E8}\u{1F1EC}", name: "Congo", format: "XX XXX XXXX" },
  { code: "+243", country: "CD", flag: "\u{1F1E8}\u{1F1E9}", name: "R.D. del Congo", format: "XXX XXX XXX" },
  { code: "+244", country: "AO", flag: "\u{1F1E6}\u{1F1F4}", name: "Angola", format: "XXX XXX XXX" },
  { code: "+258", country: "MZ", flag: "\u{1F1F2}\u{1F1FF}", name: "Mozambique", format: "XX XXX XXXX" },
  { code: "+260", country: "ZM", flag: "\u{1F1FF}\u{1F1F2}", name: "Zambia", format: "XX XXX XXXX" },
  { code: "+263", country: "ZW", flag: "\u{1F1FF}\u{1F1FC}", name: "Zimbabue", format: "XX XXX XXXX" },
  { code: "+261", country: "MG", flag: "\u{1F1F2}\u{1F1EC}", name: "Madagascar", format: "XX XX XXX XX" },
  { code: "+250", country: "RW", flag: "\u{1F1F7}\u{1F1FC}", name: "Ruanda", format: "XXX XXX XXX" },
  { code: "+252", country: "SO", flag: "\u{1F1F8}\u{1F1F4}", name: "Somalia", format: "XX XXX XXXX" },
  { code: "+253", country: "DJ", flag: "\u{1F1E9}\u{1F1EF}", name: "Yibuti", format: "XX XX XX XX" },
  { code: "+291", country: "ER", flag: "\u{1F1EA}\u{1F1F7}", name: "Eritrea", format: "X XXX XXX" },
  { code: "+265", country: "MW", flag: "\u{1F1F2}\u{1F1FC}", name: "Malaui", format: "X XXXX XXXX" },
  { code: "+267", country: "BW", flag: "\u{1F1E7}\u{1F1FC}", name: "Botsuana", format: "XX XXX XXX" },
  { code: "+264", country: "NA", flag: "\u{1F1F3}\u{1F1E6}", name: "Namibia", format: "XX XXX XXXX" },
  { code: "+268", country: "SZ", flag: "\u{1F1F8}\u{1F1FF}", name: "Esuatini", format: "XXXX XXXX" },
  { code: "+266", country: "LS", flag: "\u{1F1F1}\u{1F1F8}", name: "Lesoto", format: "XXXX XXXX" },
  { code: "+257", country: "BI", flag: "\u{1F1E7}\u{1F1EE}", name: "Burundi", format: "XX XX XXXX" },
  { code: "+238", country: "CV", flag: "\u{1F1E8}\u{1F1FB}", name: "Cabo Verde", format: "XXX XXXX" },
  { code: "+239", country: "ST", flag: "\u{1F1F8}\u{1F1F9}", name: "Santo Tomé y Príncipe", format: "XX XXXXX" },
  { code: "+240", country: "GQ", flag: "\u{1F1EC}\u{1F1F6}", name: "Guinea Ecuatorial", format: "XXX XXX XXX" },
  { code: "+245", country: "GW", flag: "\u{1F1EC}\u{1F1FC}", name: "Guinea-Bisáu", format: "XXX XXXX" },
  { code: "+231", country: "LR", flag: "\u{1F1F1}\u{1F1F7}", name: "Liberia", format: "XX XXX XXXX" },
  { code: "+232", country: "SL", flag: "\u{1F1F8}\u{1F1F1}", name: "Sierra Leona", format: "XX XXX XXX" },
  { code: "+230", country: "MU", flag: "\u{1F1F2}\u{1F1FA}", name: "Mauricio", format: "XXXX XXXX" },
  { code: "+269", country: "KM", flag: "\u{1F1F0}\u{1F1F2}", name: "Comoras", format: "XXX XXXX" },
  { code: "+248", country: "SC", flag: "\u{1F1F8}\u{1F1E8}", name: "Seychelles", format: "X XX XX XX" },
  // Oceania
  { code: "+61", country: "AU", flag: "\u{1F1E6}\u{1F1FA}", name: "Australia", format: "XXX XXX XXX" },
  { code: "+64", country: "NZ", flag: "\u{1F1F3}\u{1F1FF}", name: "Nueva Zelanda", format: "XX XXX XXXX" },
  { code: "+679", country: "FJ", flag: "\u{1F1EB}\u{1F1EF}", name: "Fiyi", format: "XXX XXXX" },
  { code: "+675", country: "PG", flag: "\u{1F1F5}\u{1F1EC}", name: "Papúa Nueva Guinea", format: "XXX XXXX" },
  { code: "+676", country: "TO", flag: "\u{1F1F9}\u{1F1F4}", name: "Tonga", format: "XXX XXXX" },
  { code: "+685", country: "WS", flag: "\u{1F1FC}\u{1F1F8}", name: "Samoa", format: "XX XXXXX" },
  { code: "+678", country: "VU", flag: "\u{1F1FB}\u{1F1FA}", name: "Vanuatu", format: "XXX XXXX" },
  { code: "+677", country: "SB", flag: "\u{1F1F8}\u{1F1E7}", name: "Islas Salomón", format: "XX XXXXX" },
  { code: "+686", country: "KI", flag: "\u{1F1F0}\u{1F1EE}", name: "Kiribati", format: "XXXX XXXX" },
  { code: "+688", country: "TV", flag: "\u{1F1F9}\u{1F1FB}", name: "Tuvalu", format: "XXXXXX" },
  { code: "+674", country: "NR", flag: "\u{1F1F3}\u{1F1F7}", name: "Nauru", format: "XXX XXXX" },
  { code: "+680", country: "PW", flag: "\u{1F1F5}\u{1F1FC}", name: "Palaos", format: "XXX XXXX" },
  { code: "+692", country: "MH", flag: "\u{1F1F2}\u{1F1ED}", name: "Islas Marshall", format: "XXX XXXX" },
  { code: "+691", country: "FM", flag: "\u{1F1EB}\u{1F1F2}", name: "Micronesia", format: "XXX XXXX" },
];

export default COUNTRY_CODES;
